### ISSUE TITLE
Updated sender

### ISSUE THREAD

**Issue by owenshen24** [0xmons/0xmons-contracts-new#20]
// Normal multisend: sends a batch of ERC-20 or ERC-721s to a list of addresses
send721Or20ToUserAddresses(address[ ] userAddresses, uint256[ ] amountOrIds, address tokenAddress, bool isERC20);

// ERC-721 targeted multisend: sends a batch of ERC-20 or ERC-721s to a list of ERC-721 ID holders
send721Or20To721(address[ ] erc721addresses, uint256[ ] ids, uint256[ ] amountOrIds, address tokenAddress, bool isERC20);

// Sends a batch of ERC-20 or ERC-721 rewards to a list of ERC-721 ID holders, to be later claimed
// Essentially "locks" tokens into the contract to be removed by the holder
send721Or20RewardsToUserAddresses(address[ ] erc721addresses, uint256[ ] ids, uint256[ ] amountOrIds, address tokenAddress, bool isERC20);

// Take the locked in reward
take721Reward(uint256 id, address tokenAddress, bool isERC20);

// Send ERC1155 to a batch of addresses
sendERC1155ToUserAddresses(address[ ] userAddresses, uint256[ ] amounts, address tokenAddress, uint256[ ] tokenIds);

// Send ERC1155 to a list of ERC-721 ID holders
sendERC1155To721(address[ ] 721addresses, uint256[ ] 721ids, uint256[ ] amounts, address tokenAddress, uint256[ ] tokenIds);

**Comment by surfer77** [comment]
Hehe had a bit of time (didn't check much or test, just wrote this here), copied your style from the swapper
```
send721Or20ToUserAddresses(address[] userAddresses, uint256[] amountOrIds, address tokenAddress, bool isERC20) {
  require((userAddresses.length == amountOrIds.length), "diff lengths");
      for (uint256 i = 0; i < userAddresses.length; i.add(1)) {
          if(isERC20) {
            IERC20(tokenAddress).safeTransferFrom(msg.sender, userAddresses[i], amountOrIds[i]);
          } else {
            IERC721(tokenAddress).safeTransferFrom(msg.sender, userAddresses[i], amountOrIds[i]);
          }
      }
}
```

**Comment by owenshen24** [comment]
Thanks! I'll use this to do the rest of them :^)
